<template>
    <v-card style="overflow: hidden;width:max-content;max-width:200%;" class="pa-10" elevation=10>
      <v-item-group multiple :value="elements" v-on:change="commitElements">
        <div style="overflow: hidden;width:max-content;padding:0px;margin:0px;" v-for="period in nums.length" :key="period">
          <div style="float:left;" v-for="group in nums[0].length" :key="group">
            <ElementBlock v-if="nums[period-1][group-1]!=0" :elcolor="elcolor[eltable[nums[period-1][group-1]]['metal']]" :number="nums[period-1][group-1]" :symbol="eltable[nums[period-1][group-1]]['symbol']" :name="eltable[nums[period-1][group-1]]['name']"></ElementBlock>
            <v-card class="ma-1" tile flat color="white" v-if="nums[period-1][group-1]==0" height="75" width="70"> </v-card>
          </div>
        </div>
      </v-item-group>
    </v-card>
</template>

<style>

</style>

<script>
import ElementBlock from '~/components/atoms/ElementBlock.vue'

export default {
    props: {'title':String,
            'editor':String,
            'startdate':String,
            'elements':Array},
    components: {
      ElementBlock,
    },
    data() {
        return {
            nums:[[1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2],
                    [3,4,0,0,0,0,0,0,0,0,0,0,5,6,7,8,9,10],
                    [11,12,0,0,0,0,0,0,0,0,0,0,13,14,15,16,17,18],
                    [19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36],
                    [37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54],
                    [55,56,0,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86],
                    [87,88,0,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118],
                    [0,0,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,0],
                    [0,0,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,0]],
            elcolor: {'nonmetal':'#404C51',
                      'noble gas':'#3A3A81',
                      'alkali metal':'#839526',
                      'alkaline earth metal':'#2E7D57',
                      'metalloid':'#861D1D',
                      'halogen':'#564620',
                      'metal':'#606060',
                      'transition metal':'#0263AD',
                      'lanthanoid':'#AA9C00',
                      'actinoid':'#7A5600'},
            eltable: {1: {'symbol': 'H', 'name': 'Hydrogen', 'metal': 'nonmetal'},
                       2: {'symbol': 'He', 'name': 'Helium', 'metal': 'noble gas'},
                       3: {'symbol': 'Li', 'name': 'Lithium', 'metal': 'alkali metal'},
                       4: {'symbol': 'Be', 'name': 'Beryllium', 'metal': 'alkaline earth metal'},
                       5: {'symbol': 'B', 'name': 'Boron', 'metal': 'metalloid'},
                       6: {'symbol': 'C', 'name': 'Carbon', 'metal': 'nonmetal'},
                       7: {'symbol': 'N', 'name': 'Nitrogen', 'metal': 'nonmetal'},
                       8: {'symbol': 'O', 'name': 'Oxygen', 'metal': 'nonmetal'},
                       9: {'symbol': 'F', 'name': 'Fluorine', 'metal': 'halogen'},
                       10: {'symbol': 'Ne', 'name': 'Neon', 'metal': 'noble gas'},
                       11: {'symbol': 'Na', 'name': 'Sodium', 'metal': 'alkali metal'},
                       12: {'symbol': 'Mg', 'name': 'Magnesium', 'metal': 'alkaline earth metal'},
                       13: {'symbol': 'Al', 'name': 'Aluminum', 'metal': 'metal'},
                       14: {'symbol': 'Si', 'name': 'Silicon', 'metal': 'metalloid'},
                       15: {'symbol': 'P', 'name': 'Phosphorus', 'metal': 'nonmetal'},
                       16: {'symbol': 'S', 'name': 'Sulfur', 'metal': 'nonmetal'},
                       17: {'symbol': 'Cl', 'name': 'Chlorine', 'metal': 'halogen'},
                       18: {'symbol': 'Ar', 'name': 'Argon', 'metal': 'noble gas'},
                       19: {'symbol': 'K', 'name': 'Potassium', 'metal': 'alkali metal'},
                       20: {'symbol': 'Ca', 'name': 'Calcium', 'metal': 'alkaline earth metal'},
                       21: {'symbol': 'Sc', 'name': 'Scandium', 'metal': 'transition metal'},
                       22: {'symbol': 'Ti', 'name': 'Titanium', 'metal': 'transition metal'},
                       23: {'symbol': 'V', 'name': 'Vanadium', 'metal': 'transition metal'},
                       24: {'symbol': 'Cr', 'name': 'Chromium', 'metal': 'transition metal'},
                       25: {'symbol': 'Mn', 'name': 'Manganese', 'metal': 'transition metal'},
                       26: {'symbol': 'Fe', 'name': 'Iron', 'metal': 'transition metal'},
                       27: {'symbol': 'Co', 'name': 'Cobalt', 'metal': 'transition metal'},
                       28: {'symbol': 'Ni', 'name': 'Nickel', 'metal': 'transition metal'},
                       29: {'symbol': 'Cu', 'name': 'Copper', 'metal': 'transition metal'},
                       30: {'symbol': 'Zn', 'name': 'Zinc', 'metal': 'transition metal'},
                       31: {'symbol': 'Ga', 'name': 'Gallium', 'metal': 'metal'},
                       32: {'symbol': 'Ge', 'name': 'Germanium', 'metal': 'metalloid'},
                       33: {'symbol': 'As', 'name': 'Arsenic', 'metal': 'metalloid'},
                       34: {'symbol': 'Se', 'name': 'Selenium', 'metal': 'nonmetal'},
                       35: {'symbol': 'Br', 'name': 'Bromine', 'metal': 'halogen'},
                       36: {'symbol': 'Kr', 'name': 'Krypton', 'metal': 'noble gas'},
                       37: {'symbol': 'Rb', 'name': 'Rubidium', 'metal': 'alkali metal'},
                       38: {'symbol': 'Sr', 'name': 'Strontium', 'metal': 'alkaline earth metal'},
                       39: {'symbol': 'Y', 'name': 'Yttrium', 'metal': 'transition metal'},
                       40: {'symbol': 'Zr', 'name': 'Zirconium', 'metal': 'transition metal'},
                       41: {'symbol': 'Nb', 'name': 'Niobium', 'metal': 'transition metal'},
                       42: {'symbol': 'Mo', 'name': 'Molybdenum', 'metal': 'transition metal'},
                       43: {'symbol': 'Tc', 'name': 'Technetium', 'metal': 'transition metal'},
                       44: {'symbol': 'Ru', 'name': 'Ruthenium', 'metal': 'transition metal'},
                       45: {'symbol': 'Rh', 'name': 'Rhodium', 'metal': 'transition metal'},
                       46: {'symbol': 'Pd', 'name': 'Palladium', 'metal': 'transition metal'},
                       47: {'symbol': 'Ag', 'name': 'Silver', 'metal': 'transition metal'},
                       48: {'symbol': 'Cd', 'name': 'Cadmium', 'metal': 'transition metal'},
                       49: {'symbol': 'In', 'name': 'Indium', 'metal': 'metal'},
                       50: {'symbol': 'Sn', 'name': 'Tin', 'metal': 'metal'},
                       51: {'symbol': 'Sb', 'name': 'Antimony', 'metal': 'metalloid'},
                       52: {'symbol': 'Te', 'name': 'Tellurium', 'metal': 'metalloid'},
                       53: {'symbol': 'I', 'name': 'Iodine', 'metal': 'halogen'},
                       54: {'symbol': 'Xe', 'name': 'Xenon', 'metal': 'noble gas'},
                       55: {'symbol': 'Cs', 'name': 'Cesium', 'metal': 'alkali metal'},
                       56: {'symbol': 'Ba', 'name': 'Barium', 'metal': 'alkaline earth metal'},
                       57: {'symbol': 'La', 'name': 'Lanthanum', 'metal': 'lanthanoid'},
                       58: {'symbol': 'Ce', 'name': 'Cerium', 'metal': 'lanthanoid'},
                       59: {'symbol': 'Pr', 'name': 'Praseodymium', 'metal': 'lanthanoid'},
                       60: {'symbol': 'Nd', 'name': 'Neodymium', 'metal': 'lanthanoid'},
                       61: {'symbol': 'Pm', 'name': 'Promethium', 'metal': 'lanthanoid'},
                       62: {'symbol': 'Sm', 'name': 'Samarium', 'metal': 'lanthanoid'},
                       63: {'symbol': 'Eu', 'name': 'Europium', 'metal': 'lanthanoid'},
                       64: {'symbol': 'Gd', 'name': 'Gadolinium', 'metal': 'lanthanoid'},
                       65: {'symbol': 'Tb', 'name': 'Terbium', 'metal': 'lanthanoid'},
                       66: {'symbol': 'Dy', 'name': 'Dysprosium', 'metal': 'lanthanoid'},
                       67: {'symbol': 'Ho', 'name': 'Holmium', 'metal': 'lanthanoid'},
                       68: {'symbol': 'Er', 'name': 'Erbium', 'metal': 'lanthanoid'},
                       69: {'symbol': 'Tm', 'name': 'Thulium', 'metal': 'lanthanoid'},
                       70: {'symbol': 'Yb', 'name': 'Ytterbium', 'metal': 'lanthanoid'},
                       71: {'symbol': 'Lu', 'name': 'Lutetium', 'metal': 'transition metal'},
                       72: {'symbol': 'Hf', 'name': 'Hafnium', 'metal': 'transition metal'},
                       73: {'symbol': 'Ta', 'name': 'Tantalum', 'metal': 'transition metal'},
                       74: {'symbol': 'W', 'name': 'Tungsten', 'metal': 'transition metal'},
                       75: {'symbol': 'Re', 'name': 'Rhenium', 'metal': 'transition metal'},
                       76: {'symbol': 'Os', 'name': 'Osmium', 'metal': 'transition metal'},
                       77: {'symbol': 'Ir', 'name': 'Iridium', 'metal': 'transition metal'},
                       78: {'symbol': 'Pt', 'name': 'Platinum', 'metal': 'transition metal'},
                       79: {'symbol': 'Au', 'name': 'Gold', 'metal': 'transition metal'},
                       80: {'symbol': 'Hg', 'name': 'Mercury', 'metal': 'transition metal'},
                       81: {'symbol': 'Tl', 'name': 'Thallium', 'metal': 'metal'},
                       82: {'symbol': 'Pb', 'name': 'Lead', 'metal': 'metal'},
                       83: {'symbol': 'Bi', 'name': 'Bismuth', 'metal': 'metal'},
                       84: {'symbol': 'Po', 'name': 'Polonium', 'metal': 'metalloid'},
                       85: {'symbol': 'At', 'name': 'Astatine', 'metal': 'halogen'},
                       86: {'symbol': 'Rn', 'name': 'Radon', 'metal': 'noble gas'},
                       87: {'symbol': 'Fr', 'name': 'Francium', 'metal': 'alkali metal'},
                       88: {'symbol': 'Ra', 'name': 'Radium', 'metal': 'alkaline earth metal'},
                       89: {'symbol': 'Ac', 'name': 'Actinium', 'metal': 'actinoid'},
                       90: {'symbol': 'Th', 'name': 'Thorium', 'metal': 'actinoid'},
                       91: {'symbol': 'Pa', 'name': 'Protactinium', 'metal': 'actinoid'},
                       92: {'symbol': 'U', 'name': 'Uranium', 'metal': 'actinoid'},
                       93: {'symbol': 'Np', 'name': 'Neptunium', 'metal': 'actinoid'},
                       94: {'symbol': 'Pu', 'name': 'Plutonium', 'metal': 'actinoid'},
                       95: {'symbol': 'Am', 'name': 'Americium', 'metal': 'actinoid'},
                       96: {'symbol': 'Cm', 'name': 'Curium', 'metal': 'actinoid'},
                       97: {'symbol': 'Bk', 'name': 'Berkelium', 'metal': 'actinoid'},
                       98: {'symbol': 'Cf', 'name': 'Californium', 'metal': 'actinoid'},
                       99: {'symbol': 'Es', 'name': 'Einsteinium', 'metal': 'actinoid'},
                       100: {'symbol': 'Fm', 'name': 'Fermium', 'metal': 'actinoid'},
                       101: {'symbol': 'Md', 'name': 'Mendelevium', 'metal': 'actinoid'},
                       102: {'symbol': 'No', 'name': 'Nobelium', 'metal': 'actinoid'},
                       103: {'symbol': 'Lr', 'name': 'Lawrencium', 'metal': 'transition metal'},
                       104: {'symbol': 'Rf', 'name': 'Rutherfordium', 'metal': 'transition metal'},
                       105: {'symbol': 'Db', 'name': 'Dubnium', 'metal': 'transition metal'},
                       106: {'symbol': 'Sg', 'name': 'Seaborgium', 'metal': 'transition metal'},
                       107: {'symbol': 'Bh', 'name': 'Bohrium', 'metal': 'transition metal'},
                       108: {'symbol': 'Hs', 'name': 'Hassium', 'metal': 'transition metal'},
                       109: {'symbol': 'Mt', 'name': 'Meitnerium', 'metal': 'transition metal'},
                       110: {'symbol': 'Ds', 'name': 'Darmstadtium', 'metal': 'transition metal'},
                       111: {'symbol': 'Rg', 'name': 'Roentgenium', 'metal': 'transition metal'},
                       112: {'symbol': 'Cn', 'name': 'Copernicium', 'metal': 'transition metal'},
                       113: {'symbol': 'Nh', 'name': 'Nihomium', 'metal': 'metal'},
                       114: {'symbol': 'Fl', 'name': 'Flerovium', 'metal': 'metal'},
                       115: {'symbol': 'Mc', 'name': 'Moscovium', 'metal': 'metal'},
                       116: {'symbol': 'Lv', 'name': 'Livermorium', 'metal': 'metal'},
                       117: {'symbol': 'Ts', 'name': 'Tennessine', 'metal': 'halogen'},
                       118: {'symbol': 'Og', 'name': 'Oganesson', 'metal': 'noble gas'}}
        }
    },
    methods: {
      commitElements: function (val) {
          this.$emit('changeElement', val);
      }
  }
}
</script>
